<a href="https://colab.research.google.com/github/RoshnaGeorge/ML/blob/main/Lab02_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A1: Purchase Data Analysis using Linear Algebra


In [35]:
import pandas as pd
import numpy as np


In [36]:
# Load the Purchase data worksheet
purchase_data = pd.read_excel("Lab Session Data.xlsx", sheet_name="Purchase data")

purchase_data.head()

,Customer,Candies (#),Mangoes (Kg),Milk Packets (#),Payment (Rs),Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Candy,Mango,Milk
0,C_1,20,6,2,386,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,55.0,18.0
1,C_2,16,3,6,289,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C_3,27,6,2,393,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,C_4,19,1,2,110,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,C_5,24,4,2,280,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [37]:
## Segregating the Data into Feature Matrix X and Output Vector y
X = purchase_data[['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']].values

y = purchase_data['Payment (Rs)'].values

print("Feature Matrix X:")
print(X)

print("\nOutput Vector y:")
print(y)

Feature Matrix X:
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]

Output Vector y:
[386 289 393 110 280 167 271 274 148 198]


1.What is the dimensionality of the vector space for this data?

The dimensionality of a vector space is the number of features in each observation. Here, each customer has 3 features: Candies (#), Mangoes (Kg), and Milk Packets (#). Therefore, the dimensionality of the vector space is 3.

In [38]:
# dimensionality of the vector space
print("Shape of X:", X.shape)
print("Dimensionality of the vector space:", X.shape[1])

Shape of X: (10, 3)
Dimensionality of the vector space: 3


2.How many vectors exist in this vector space?

Each row in the feature matrix X represents one observation vector or one customer's purchase. Since the matrix has 10 rows, there are 10 observation vectors, and each vector has 3 dimensions.

In [39]:
# Find the number of observation vectors
number_of_vectors = X.shape[0]

print("Number of observation vectors:", number_of_vectors)

Number of observation vectors: 10


3.What is the rank of Matrix A? How to calculate rank of a matrix? Calculate the
rank of the feature matrix.



*   The rank of a matrix is the maximum number of linearly independent rows or columns in the matrix
*   The rank can be calculated manually by converting the matrix into Row Echelon Form and counting the number of non-zero rows.






4.Calculate the rank of the feature matrix with numpy package

In [40]:
# Calculate the rank of the feature matrix X
rank_X = np.linalg.matrix_rank(X)

print("Rank of feature matrix X:", rank_X)

Rank of feature matrix X: 3


The calculated rank is 3. This means the three feature columns are linearly independent.

5.Using Pseudo-Inverse find the cost of each product available for sale.

In [41]:
# Cost of Each Product Using Pseudo-Inverse
X_pseudo_inverse = np.linalg.pinv(X)

product_costs = X_pseudo_inverse @ y

print("Cost of one Candy: Rs.", product_costs[0])
print("Cost of 1 kg Mango: Rs.", product_costs[1])
print("Cost of one Milk Packet: Rs.", product_costs[2])

Cost of one Candy: Rs. 0.9999999999999989
Cost of 1 kg Mango: Rs. 54.99999999999999
Cost of one Milk Packet: Rs. 18.0


### Conclusion

* The Purchase Data contains 10 observation vectors with 3 features.
* The dimensionality of the vector space is 3.
* The rank of the feature matrix X is 3, indicating that the three feature columns are linearly independent.
* Using the pseudo-inverse method, the individual product costs were calculated.
   * The cost of one Candy: ~ Rs. 1.
   * The cost of 1 kg of Mango: ~ Rs. 55.
   * The cost of one Milk Packet: Rs. 18.
